name: Python Lint

on:
  push:
    branches: [main]
      workflow_dispatch: 

jobs:
  Validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
        
      - name: Install Dependencies
        working-directory: .github/workflows
        run: pip install -r requirements.txt
        
      
